#define IDC_WARFRONT_WF_HEADER		1000
#define IDC_WARFRONT_WF_HEADERNAME	1001
#define IDC_WARFRONT_WF_MAP		1200
#define IDC_WARFRONT_WF_BACKGROUND	2200
#define IDC_WARFRONT_WF_CHECKBTN		2400
#define IDC_WARFRONT_WF_PLACERALLYBTN	2401
#define IDC_WARFRONT_WF_JUMPBTN		2402
#define IDC_WARFRONT_WF_CLOSEBTN		2404











